### ISSUE TITLE
Scrolling jumps to top when writing in editor

### ISSUE THREAD

**Issue by davidADSP** [bcherny/better-asciidoctor-vscode#5]
On the latest version of VSCode (1.26, July), the preview display jumps to the top of the document when you write in the editor.

**Comment by bcherny** [comment]
Interesting - I’m on the same version, but am not seeing this issue. A potential fix is implementing #3 — want to give it a shot?

**Comment by bcherny** [comment]
I can repro this consistently now. Will look into it.

**Comment by davidADSP** [comment]
Is there a fix for this?

**Comment by bcherny** [comment]
Please vote on (or help fix) above VSCode issue

**Comment by bcherny** [comment]
This is fixed on the latest VSCode Insiders build (1.28.0-inside), and will be in the next VSCode release. For now, I downloaded the latest Insiders build to get the fix early:

https://code.visualstudio.com/insiders/
